bigone/__init__.py,sha256=nHf3BDq50a4ABaqs64gPYjmiNKF2wPJ9r7NcOfpuNmI,116
bigone/client.py,sha256=RavQRe44Jd2kgCBiuJ5M74vjaLakAUWbEuj0pCLrjGY,23066
bigone/exceptions.py,sha256=geIeGk1TX4udDtF8yo9ZbjMz8shKqlvNiJ6Vi18yFaI,1435
python_bigone-0.1.0.dist-info/DESCRIPTION.rst,sha256=OCTuuN6LcWulhHS3d5rfjdsQtW22n7HENFRh6jC6ego,10
python_bigone-0.1.0.dist-info/METADATA,sha256=v75mV8VTvE88C6oEdHPTg1N6Y0mAql_c9kJJnXM9Qz0,905
python_bigone-0.1.0.dist-info/RECORD,,
python_bigone-0.1.0.dist-info/WHEEL,sha256=kdsN-5OJAZIiHN-iO4Rhl82KyS0bDWf4uBwMbkNafr8,110
python_bigone-0.1.0.dist-info/metadata.json,sha256=MjZax8d_H1LqDS-WnvzTEuPimAU73ib4eS-JI9ZF0k0,1034
python_bigone-0.1.0.dist-info/top_level.txt,sha256=oIrxLUvBbRLG80guL5XQ-9U6E1Y58Yo8ywT1hnStwys,7
